### ISSUE TITLE
Error in remove_technical_variation function

### ISSUE THREAD

**Issue by miraSeasideX** [sritchie73/ukbnmr#11]
Hi, when i'm running the function remove_technical_variation, error happens. I´ve followed the steps as outlined in the readme to the letter; it doesnt happen with the toy data, but only with the full UKB dataset. This data has however been decoded using the standard steps, nothing custom. Any idea what step/input this involves, and maybe how to resolve this?
Thanks. Best, Haibin.

Adjusting for drift over time within spectrometer...
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])

**Comment by sritchie73** [comment]
Hi Haibin,

Are you using the RAP or data on your local machine/cluster?

**Comment by miraSeasideX** [comment]
> Hi Haibin,
> 
> Are you using the RAP or data on your local machine/cluster?

Thanks for your reply.
I'm using data on my local machine. i've figured out this problem. The bug was caused because field ID 23649 was recognized as a numeric variable. After converting it to a character type, the function runs correctly. 

Additionally, I have another problem: when performing log and z-transformations on biomarkers after remove_technical_variation function, some values become infinite. What’s the best way to handle these infinite values?

**Comment by sritchie73** [comment]
> Thanks for your reply. I'm using data on my local machine. i've figured out this problem. The bug was caused because field ID 23649 was recognized as a numeric variable. After converting it to a character type, the function runs correctly.

Thanks, that's helpful to know. I'll add some hard coded checks to work around this for others who have the problem in the future.

> Additionally, I have another problem: when performing log and z-transformations on biomarkers after remove_technical_variation function, some values become infinite. What’s the best way to handle these infinite values?

Some of the biomarkers have concentrations of 0, which when log transformed will give Infinite values. You can add a small offset to these biomarkers so that the log transformation gives finite values. The `remove_technical_variation()` function returns a table of suggested offsets to use for this, in the `log_offset` table: the offsets returned are 0.5 * the smallest non-zero value for each biomarker, and are what we use internally when log transforming the biomarkers before removing the technical variation.

**Comment by miraSeasideX** [comment]
> > Thanks for your reply. I'm using data on my local machine. i've figured out this problem. The bug was caused because field ID 23649 was recognized as a numeric variable. After converting it to a character type, the function runs correctly.
> 
> Thanks, that's helpful to know. I'll add some hard coded checks to work around this for others who have the problem in the future.
> 
> > Additionally, I have another problem: when performing log and z-transformations on biomarkers after remove_technical_variation function, some values become infinite. What’s the best way to handle these infinite values?
> 
> Some of the biomarkers have concentrations of 0, which when log transformed will give Infinite values. You can add a small offset to these biomarkers so that the log transformation gives finite values. The `remove_technical_variation()` function returns a table of suggested offsets to use for this, in the `log_offset` table: the offsets returned are 0.5 * the smallest non-zero value for each biomarker, and are what we use internally when log transforming the biomarkers before removing the technical variation.

I am not sure if my understanding is correct: should the 0 values in the biomarkers be replaced with the Log.Offset from the og_offset table? Is there any reference code available? Thank you very much!

**Comment by sritchie73** [comment]
No, you need to shift all values of the given biomarker by the respective Log.Offset (i.e. so that the rank ordering of samples is preserved). 

Using the log offset values determined from the first release on 120k participants (e.g. see Table S4 in https://www.nature.com/articles/s41597-023-01949-y) your code might look something like:

```
library(data.table)

# Here, 'qced' is the data.table returned by the remove_technical_variation() function
qced[, Clinical_LDL_C := Clinical_LDL_C + 0.019368] # or qced[["Clinical_LDL_C"]] <- qced[["Clinical_LDL_C"]] + 0.019368 if you're not familiar with data.table notation
qced[, bOHbutyrate := bOHbutyrate + 0.00000140325]
qced[, Acetate := Acetate + 0.000001065]
qced[, Acetoacetate := Acetoacetate + 0.0000007114]
qced[, L_LDL_CE := L_LDL_CE + 0.000000059445]
qced[, L_LDL_FC := L_LDL_FC + 0.00000000000405315]
qced[, M_LDL_CE := M_LDL_CE + 0.00000000000384805]
```

N.b. this is just one of several possible methods for handling log transformations for data that contain 0 values, e.g. see https://aosmith.rbind.io/2018/09/19/the-log-0-problem/ for discussion and alternatives.

**Comment by sritchie73** [comment]
> > Thanks for your reply. I'm using data on my local machine. i've figured out this problem. The bug was caused because field ID 23649 was recognized as a numeric variable. After converting it to a character type, the function runs correctly.
>
> Thanks, that's helpful to know. I'll add some hard coded checks to work around this for others who have the problem in the future.

Hi @miraSeasideX , following up on this, the package already has checks in place for and handling the condition where field 23649 was loaded as a numeric column instead of a character column.

It would be helpful if I could see what the data you've loaded into R looks like before you fix the column types to help me diagnose why the existing checks and conversions haven't worked.

Can you run the following and copy the output here?

```
print(str(na.omit(decoded[["23649-0.0"]])))
print(str(na.omit(decoded[["23649-1.0"]])))
```

Here 'decoded' is the data.frame/data.table of the data you've loaded into R before running any of the ukbnmr package functions. The column names may also need modifying depending on how the UKB data was decoded or loaded into R. (e.g. they might be "f23649.0.0" and "f23649.1.0" instead of "23649-0.0" and "23649-1.0")

**Comment by miraSeasideX** [comment]
``> > > Thanks for your reply. I'm using data on my local machine. i've figured out this problem. The bug was caused because field ID 23649 was recognized as a numeric variable. After converting it to a character type, the function runs correctly.
> > 
> > 
> > Thanks, that's helpful to know. I'll add some hard coded checks to work around this for others who have the problem in the future.
> 
> Hi @miraSeasideX , following up on this, the package already has checks in place for and handling the condition where field 23649 was loaded as a numeric column instead of a character column.
> 
> It would be helpful if I could see what the data you've loaded into R looks like before you fix the column types to help me diagnose why the existing checks and conversions haven't worked.
> 
> Can you run the following and copy the output here?
> 
> ```
> print(str(na.omit(decoded[["23649-0.0"]])))
> print(str(na.omit(decoded[["23649-1.0"]])))
> ```
> 
> Here 'decoded' is the data.frame/data.table of the data you've loaded into R before running any of the ukbnmr package functions. The column names may also need modifying depending on how the UKB data was decoded or loaded into R. (e.g. they might be "f23649.0.0" and "f23649.1.0" instead of "23649-0.0" and "23649-1.0")

> print(str(na.omit(decoded[["23649-0.0"]])))
 num [1:274245] 4.9e+11 4.9e+11 4.9e+11 4.9e+11 4.9e+11 ...
 - attr(*, "na.action")= 'omit' int [1:227899] 3 5 6 10 13 15 17 19 20 21 ...
NULL
> print(str(na.omit(decoded[["23649-1.0"]])))
 NULL
NULL

It seems that something wrong happened when the data were loaded. BTW, I only use data in instance 1.

**Comment by sritchie73** [comment]
Ah, the `remove_technical_variation()` function needs to be run before you filter to instance 1, which you can do after the fact by filtering on the visit_index column to visit_index == 1.

**Comment by miraSeasideX** [comment]
> Ah, the `remove_technical_variation()` function needs to be run before you filter to instance 1, which you can do after the fact by filtering on the visit_index column to visit_index == 1.

Ah ha, I think I have to run all the analysis again. Thanks for your reply again!
