### ISSUE TITLE
Question regarding Missing QC/Processing Columns

### ISSUE THREAD

**Issue by jdjmoon** [sritchie73/ukbnmr#4]
Hello,

After updating my DNAnexus dataset recently, I have found out that certain NMR QC Flag columns and Processing Columns seem to be missing (such as Total Cholesterol, QC Flag (Field 23700). Under the current situation, I'm curious whether there's a possibility to still utilize the package, or if it exclusively functions with complete columns.

Thank you in advance for your valuable assistance!

**Comment by sritchie73** [comment]
Hi @jdjmoon ,

The functions should be robust to missing NMR QC flag fields - many of these are empty to begin with; e.g. No QC flags were generated by Nightingale Health for any of the Total Cholesterol measurements (0 items listed on the UKB showcase; https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=23700); so these fields will not be present when you extract the data using the UK Biobank's ukbconv tool. The package functions should return columns filled with NAs for these.

Some of the sample processing flags are required for the `remove_technical_variation()` function to run, but this function will check for these in your data and return an error if they are missing. If you want to check in advance, the key fields you need are 23658, 23659, 23649, and 23660 if you're running algorithm version 1 (designed for the initial ~120K participant data release) and also field 20282 if you're running algorithm version 2 (designed for the updated ~275K participant data release).

**Comment by jdjmoon** [comment]
Thank you for your quick response. I am currently running algorithm version 2 using the updated dataset, and I have included the missing NMR QC flag fields with columns containing NaN values as recommended above. However, I've noticed that the Key field 20282 is missing from my side of the DNAnexus dataset. Given this situation, should I consider running algorithm version 1 instead?

**Comment by sritchie73** [comment]
Hi @jdjmoon 

I've just pushed an update to the package so that it will infer the missing Processing Batch data field from the Shipment Plate field 23649. 

It seems like when UK Biobank refreshes the baskets with updated data they don't include any new fields, so people have to be aware of these and request these, so most people are currently missing field 20282, and I realised it should be possible to create this sort of direct mapping to get around the issue.

Can you try reinstalling from latest version from this GitHub and run remove_technical_variation? It should spit out a warning that it is inferring Processing Batch from Shipment Plate, and then a second warning will occur if this mapping fails.

**Comment by jdjmoon** [comment]
Thank you for the update. It seems that the package is currently running smoothly without any issues with the warning you mentioned above: 

"Warning messages:
1: In remove_technical_variation(met1) :
  Processing.Batch missing (Field 20282), inferring from Shipment.Plate (Field 23649)
2: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion".

Thank you again for the update
