### ISSUE TITLE
NMR biomarker fields (#23400-23648) not found in input data from nmr <- extract_biomarkers(decoded)

### ISSUE THREAD

**Issue by anbai106** [sritchie73/ukbnmr#9]
Hi,

I downloaded the most recent NMR data from UKB-RAP (I did not use the ukbconv or ukbtools), and got the error when running the first function:

> decoded <- read.table(tsv, header=T, sep='\t', check.names = FALSE)
nmr <- extract_biomarkers(decoded)

"Browse[2]> nmr <- extract_biomarkers(decoded)
Error in detect_format(x, type = "biomarkers") : 
  NMR biomarker fields (#23400-23648) not found in input data"

I have tried to make sure the data frame decoded is similar as the doc: 
`Data sets extracted by ukbconv have one row per UKB biobank participant whose project specific sample identifier is given in the first column named "eid". Columns following this have the format "<field_id>-<visit_index>.<repeat_index>", where here <field_id> corresponds to a biomarker of interest, e.g. 23474 for 3-Hydroxybutyrate, <visit_index> corresponds to the assessment time point, e.g. 0 for baseline assessment, 1 for first repeat visit. For the UKB NMR data, the <repeat_index> column is reserved for cases where biomarker measurements have more than one QC Flag (see extract_biomarker_qc_flags()).`

Any idea?

Thanks

**Comment by anbai106** [comment]
I found the bug! Reading the toy data, I figured out the correct form of the input data! You can close this now

**Comment by sritchie73** [comment]
Hi @anbai106 , 

Glad you were able to work around the current limitations of the expected input data format

Getting the package to work on the UKB RAP is very much on my TODO list. 

I'm still in the process of working out how to use the RAP, but I've taken a stab at updating the package to work with the extracted phenotype data on the RAP based on the RAP documentation.

Since you already have the phenotype data extracted (which I haven't worked out how to do yet), it would be helpful if you could try running with my test branch, which can be installed by running `remotes::install_github("sritchie73/ukbnmr", "UKB_RAP")`.

The package from this test branch is updated to detect column names of the format "p23400_i0" etc. instead of expecting "f23400-0.0" as the column name format.
